# Generated by Django 6.0.3 on 2026-04-01 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN must be 10 or 13 digits (hyphens are allowed).', regex='^(?=(?:\\D*\\d){10}$|(?:\\D*\\d){13}$)[-\\d]+$')]),
        ),
    ]
